### ISSUE TITLE
动画结束后定时器并没有关闭

### ISSUE THREAD

**Issue by zhoupIT** [clairehu7/PieChart#1]
你可以测了看看

**Comment by clairehu7** [comment]
在 HKPieChartView.m 中添加了 - dealloc 方法 和 - removeFromSuperview 方法

**Comment by zhoupIT** [comment]
因为以前定时器经常遇到这个问题,看到你这也写了,我就打印了一下.

**Comment by clairehu7** [comment]
感谢！
